// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;

namespace Tarningspel
{

    class Program
    {
        static Random random = new Random();

        static void Main(string[] args)
        {
            Console.WriteLine("Välkommen till Tärningsspelet Pro!");

            // -Match inställningar-

            Console.WriteLine("Hur många spelare? ");
            int antalSpelare = int.Parse(Console.ReadLine());

            List<string> spelarnamn = new List<string>();
            for (int i = 0; i < antalSpelare; i++)
            {
                Console.WriteLine($"Namn på spelare {i + 1}: ");
                spelarnamn.Add(Console.ReadLine());
            }

            Console.WriteLine("Hur många tärningar per slag? ");
            int antalTarningar = int.Parse(Console.ReadLine());

            Console.Write("Vilken poäng ska man nå för att vinna? ");
            int malPoang = int.Parse(Console.ReadLine());

            List<int> spelarePoang = new List<int>(new int[antalSpelare]);
            bool spelPagar = true;

            // --- Spelloop ---

            while (spelPagar)
            {
                for (int i = 0; i < antalSpelare; i++)
                {
                    Console.WriteLine("\n--- " + spelarnamn[i] + " s tur ---");

                    int poang = SlaTarningar(antalTarningar);

                    spelarePoang[i] += poang;

                    Console.WriteLine($"{spelarnamn[i]} har nu {spelarePoang[i]} poäng");

                    Console.WriteLine("Tryck Enter för nästa spelares tur...");
                    Console.ReadLine();

                    if (spelarePoang[i] >= malPoang)
                    {
                        Console.WriteLine($"\n {spelarnamn[i]} har vunnit med {spelarePoang[i]} poäng!");
                        spelPagar = false;
                        break;
                    }
                }
            }
        //--- När spelet är slut ---
            Console.WriteLine("\nSpelet är slut!");

        }

    static int SlaTarningar(int antal)
        {
            int totalPoang = 0;
            int[] tarningar = new int[antal];

            Console.WriteLine("Du slår tärningarna...");
            Console.ReadKey();

            for (int i = 0; i < antal; i++)
                tarningar[i] = random.Next(1, 7);

            Console.WriteLine("Resultat:");
            for (int i = 0; i < antal; i++)
            {
                Console.Write(tarningar[i]);
                if (i < antal -1) Console.Write(", ");
            }
            Console.WriteLine("");

            for (int i = 0; i < antal; i++)
            {
                if (tarningar[i] == 1) totalPoang += 100;
                else if (tarningar[i] == 5) totalPoang += 50;
            }

            // --- Bonusar ---

            int[] antalAv = new int[7];
            foreach (int varde in tarningar) antalAv[varde]++;

            for (int i = 1; i <= 6; i++)
            {
                if (antalAv[i] >= 3)
                {
                    if (antalAv[i] == 5)
                    {
                        Console.WriteLine("ALLA LIKA! 1000 BONUSPOÄNG");
                        totalPoang += 1000;
                    }
                    else
                    {
                        Console.WriteLine($"Triss i {i} ger 300 bonuspoäng!");
                        totalPoang += 300;
                    }
                }
            }
            Array.Sort(tarningar);
            if (antal == 3 && (tarningar.SequenceEqual(new int[] { 1, 2, 3 }) ||
                tarningar.SequenceEqual(new int[] { 4, 5, 6 })))
            {
                Console.WriteLine("Stege! 450 bonuspoäng!");
                totalPoang += 450;
            }

            if (tarningar.All(x => x % 2 == 0) || tarningar.All(x => x % 2 == 1))
            {
                Console.WriteLine("Alla tärningar udda eller jämna! +150 poäng!");
                totalPoang += 150;
            }

            if (antalAv[1] >= 1 && antalAv[5] >= 1)
            {
                Console.WriteLine("Du fick både 1 och 5! Du får slå en extra gång!");
                Console.ReadKey();
                totalPoang += SlaTarningar(antal);
            }

            Console.WriteLine($"Poäng denna omgång: {totalPoang}");
            return totalPoang;
        }
    }
}